"use client";
import { PersistGate } from "redux-persist/integration/react";
import "./globals.css";

import StoreProvider from "./StoreProvider";

import { ToastContainer } from "react-toastify";
import { persistor } from "./lib/store";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <StoreProvider>
          <PersistGate loading={null} persistor={persistor}>
            {children}
          </PersistGate>

          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
